version: '1.0'
name: pipeline-deploy
displayName: pipeline-deploy
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-deploy
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - npm install && npm run build:web
          - '# 执行编译命令'
          - echo "复制项目"
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./search
        caches: []
        notify: []
        strategy:
          retry: '0'
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: e-start-web
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_nodejs
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: uk
          hostID:
            - f19b94c6-6c8f-4882-a9da-095128431c9e
        deployArtifact:
          - source: build
            name: e-start-web
            target: ~/gitee_go/deploy
            dependArtifact: BUILD_ARTIFACT
        script:
          - '# 先进入项目目录'
          - 'mkdir -p /www/wwwroot/e-start'
          - 'cd /www/wwwroot/e-start'
          - '# 更新源码 (可选，如果 start.sh 需要最新源码)'
          - 'git pull || echo "Warning: git pull failed, using existing code."'
          - '# 清理旧的前端产物'
          - 'rm -rf search'
          - '# 解压最新的前端产物'
          - 'tar zxvf ~/gitee_go/deploy/e-start-web.tar.gz -C ./'
          - '# 赋予启动脚本执行权限'
          - 'chmod +x start.sh'
          - '# 启动服务 (生产模式)'
          - 'nohup bash start.sh production > deploy.log 2>&1 &'
          - 'echo "部署完成! 请查看 deploy.log 获取启动详情。"'
        notify: []
        strategy:
          retry: '0'
        dependsOn: publish_general_artifacts
