/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/sidebar/setting/about.vue')['default']
    Add: typeof import('./components/sidebar/add.vue')['default']
    AppGroupNav: typeof import('./components/app-group-nav.vue')['default']
    DateTime: typeof import('./components/date-time.vue')['default']
    Default: typeof import('./components/sidebar/add/default.vue')['default']
    DIcon: typeof import('./components/public/d-icon.vue')['default']
    DModal: typeof import('./components/public/d-modal.vue')['default']
    DTabs: typeof import('./components/public/d-tabs.vue')['default']
    Exterior: typeof import('./components/sidebar/setting/exterior.vue')['default']
    Fm: typeof import('./components/fm.vue')['default']
    Header: typeof import('./components/header.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    Music: typeof import('./components/music.vue')['default']
    Note: typeof import('./components/sidebar/note.vue')['default']
    Pinned: typeof import('./components/pinned.vue')['default']
    SearchBox: typeof import('./components/search-box.vue')['default']
    Setting: typeof import('./components/sidebar/setting/index.vue')['default']
    Sidebar: typeof import('./components/sidebar/index.vue')['default']
    Theme: typeof import('./components/sidebar/setting/theme.vue')['default']
    Todo: typeof import('./components/sidebar/todo.vue')['default']
    User: typeof import('./components/sidebar/setting/user.vue')['default']
    Wallpaper: typeof import('./components/sidebar/setting/wallpaper.vue')['default']
    Weather: typeof import('./components/sidebar/weather.vue')['default']
    Yiyan: typeof import('./components/yiyan.vue')['default']
  }
}
